source $HOME/.config/zsh/env.zsh
source $HOME/.config/zsh/aliases.zsh
source $HOME/.config/zsh/fzf.zsh
source $HOME/.config/zsh/clash.zsh
source $HOME/.config/zsh/yazi.zsh

# ZSH_THEME="crcandy"
ZSH_THEME="passion"

plugins=(
    zsh-autosuggestions
    zsh-syntax-highlighting
    )

source ~/.oh-my-zsh/oh-my-zsh.sh
source ~/.config/zsh/completion.zsh
